version: "3"
services:
  mongo:
    image: mongo:3-stretch
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
#      - "./data:/data/db"
      - "mongo_data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: p@ssword
    restart: always
    network_mode: bridge

volumes:
  mongo_data:
    driver: local
