# noteguest
# run commands before
# echo never > /sys/kernel/mm/transparent_hugepage/enabled
# echo never > /sys/kernel/mm/transparent_hugepage/defrag
# sysctl vm.overcommit_memory=1

version: "3"
services:
  redis_service:
    image: redis:4
    container_name: redis
    volumes:
      - "./redis_data:/data"
      - "./conf/redis.conf:/usr/local/etc/redis/redis.conf"
    ports:
      - "6379:6379"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    restart: always
    network_mode: bridge
    sysctls:
      - net.core.somaxconn=65535