version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "data:/var/lib/rabbitmq"
      - "./conf:/etc/rabbitmq_conf"
      - "log:/var/log/rabbitmq:rw"
    environment:
      - RABBITMQ_CONF_ENV_FILE=/etc/rabbitmq_conf/rabbitmq-env.conf
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq_conf/rabbitmq
    restart: always

volumes:
  log:
  data:
