version: '3.3'
services:
  mysql:
    build: .
    restart: always
    environment:
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - "./data:/var/lib/mysql"
    command: "--innodb_use_native_aio=0"
    network_mode: bridge