global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is


alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: node_prometheus
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/tls/ca.crt
      cert_file: /etc/prometheus/tls/prometheus.crt
      key_file: /etc/prometheus/tls/prometheus_nopass.key
    file_sd_configs:
    - files:
      - /etc/prometheus/file_sd_configs/target_*.json
      refresh_interval: 60s