version: '2'
services:  
  mysql_service:
    image: mysql:5.7   
    container_name: mysql_service  
    volumes:
        - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    restart: always
    network_mode: bridge
    
volumes:
  mysql-data:
